apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  annotations:
    appstudio.openshift.io/application: integ-app-ztxb
    appstudio.openshift.io/component: integration-suite-test-component-git-source-qapm
    build.appstudio.openshift.io/build: "true"
    build.appstudio.openshift.io/type: build
    build.appstudio.openshift.io/version: "0.1"
    pipelines.appstudio.openshift.io/type: build
  creationTimestamp: null
  name: integration-suite-test-component-git-source-qapm
  namespace: integ-e2e-vlqd
spec:
  namespaceSelector: {}
  resources: {}
  serviceAccountName: pipeline
  triggers:
  - bindings:
    - kind: ClusterTriggerBinding
      ref: github-push
    template:
      ref: integration-suite-test-component-git-source-qapm
status:
  configuration:
    generatedName: ""
